import { appRouter } from "@answeroverflow/api";
import { createSSGContext } from "@answeroverflow/api/src/router/context";
import { MessageResultPage } from "@answeroverflow/ui";
import { createProxySSGHelpers } from "@trpc/react-query/ssg";
import Head from "next/head";
import superjson from "superjson";
import { trpc } from "@answeroverflow/ui";
import type { GetStaticPropsContext, InferGetStaticPropsType } from "next";

export default function MessageResult(props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { message_id } = props;
  const postQuery = trpc.message_page.byId.useQuery(message_id);
  if (postQuery.status !== "success") {
    // won't happen since we're using `fallback: "blocking"`
    return <>Loading...</>;
  }
  const { data } = postQuery;
  const { messages, parent_channel, server, thread } = data;

  return (
    <>
      <Head>
        <title>Answer Overflow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MessageResultPage
        messages={messages}
        channel={parent_channel}
        server={server}
        thread={thread}
      />
    </>
  );
}

export function getStaticPaths() {
  return { paths: [], fallback: "blocking" };
}

export async function getStaticProps(context: GetStaticPropsContext<{ message_id: string }>) {
  const ssg = createProxySSGHelpers({
    router: appRouter,
    ctx: await createSSGContext(),
    transformer: superjson, // optional - adds superjson serialization
  });
  if (!context.params) {
    return {
      notFound: true,
    };
  }
  // prefetch `post.byId`
  await ssg.message_page.byId.prefetch(context.params.message_id);
  return {
    props: {
      trpcState: ssg.dehydrate(),
      message_id: context.params.message_id,
    },
    revalidate: 60 * 10, // every 10 minutes
  };
}
