import { appRouter } from "@answeroverflow/api";
import { createSSGContext } from "@answeroverflow/api/src/router/context";
import { Message } from "@answeroverflow/ui";
import { createProxySSGHelpers } from "@trpc/react-query/ssg";
import type { InferGetStaticPropsType } from "next";
import Head from "next/head";
import superjson from "superjson";
import { trpc } from "../utils/trpc";

export default function Home(props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { id } = props;
  const postQuery = trpc.messages.byId.useQuery(id);
  if (postQuery.status !== "success") {
    // won't happen since we're using `fallback: "blocking"`
    return <>Loading...</>;
  }
  const { data } = postQuery;

  return (
    <>
      <Head>
        <title>Answer Overflow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div>
          <Message
            message={{
              id,
              channel_id: "",
              server_id: "",
              content: data.content,
              images: [],
              solutions: [],
              author: {
                name: "Rhys",
                id: "10",
                avatar: undefined,
              },
              replies_to: undefined,
              thread_id: undefined,
              child_thread: undefined,
              reply_count: undefined,
            }}
          />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const ssg = createProxySSGHelpers({
    router: appRouter,
    ctx: await createSSGContext(),
    transformer: superjson, // optional - adds superjson serialization
  });
  const id = "1062719309673140394";
  // prefetch `post.byId`
  await ssg.messages.byId.prefetch(id);
  return {
    props: {
      trpcState: ssg.dehydrate(),
      id,
    },
    revalidate: 1,
  };
}
