version: '3.8'

# Extra services to run that aren't required
name: "answeroverflow_devcontainer" # <--- this
services:
  kibana:
    name: ao-db-kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://ao-db-elastic:9200
      - COMPOSE_PROJECT_NAME
    depends_on:
      - db-elastic
    expose:
      - 5601
    ports:
      - 5601:5601
