# fly.toml app configuration file generated for answeroverflow on 2024-06-15T14:04:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'answeroverflow'
primary_region = 'iad'

[build]
  dockerfile = 'apps/main-site/Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
