version: '3.8'

# Extra services to run that aren't required
services:
  kibana:
    container_name: ao-db-kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://ao-db-elastic:9200
      - COMPOSE_PROJECT_NAME
    depends_on:
      - db-elastic
    expose:
      - 5601
    ports:
      - 5601:5601
  db-elastic:
    container_name: ao-db-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          memory: 2048m
        reservations:
          memory: 1024m
