name = "answeroverflow-main-site"
main = "worker.ts"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "answeroverflow-main-site"

[images]
binding = "IMAGES"
