name: Quick Idea
description: Jot down a quick concept to add to the backlog. Ideas that do not fit the other categories should go here
title: "[Needs Expansion]: "
labels: ["🔬Needs Expansion"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What is the idea?
      placeholder: It should...
    validations:
      required: true
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solutions
      description: How could this be solved?
      placeholder: You could use the...
  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: Post any extra links, screenshots, or references that might be helpful here
      placeholder: This component looks like a good refrence https://www.youtube.com/watch?v=dQw4w9WgXcQ
    validations:
      required: false
