name: Website
description: Create an feature request for the website
title: "[Web]:"
labels: ["🖥️website"]
body:
  - type: dropdown
    id: aspect
    attributes:
      label: aspect
      description: What aspect of the website does this relate to?
      multiple: true
      options:
        - Server Dashboard
        - Message Result Page
        - Homepage
        - Search Results
        - Server Community Page
        - Other
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Suggestion?
      description: What changes would you like to see?
      placeholder: Make the message result page...
    validations:
      required: true
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solutions
      description: Got ideas for how to solve this?
      placeholder: If there is a solution then...
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: Post any extra links, screenshots, or references that might be helpful here
      placeholder: I like how they implement it here https://www.youtube.com/watch?v=dQw4w9WgXcQ...
    validations:
      required: false
