import { cn } from "../../../lib/utils";

export const FeaturesSection = (props: { className?: string }) => {
	return (
		<div className={cn("w-full", props.className)}>
			<h2 className="text-center md:text-right">
				Tools tailored to your community
			</h2>
			<h3 className="pt-0 text-center text-lg md:text-right">
				Your community is unique, it's time you had a bot that matches it
			</h3>

			<div className="mt-2 grid grid-cols-1 grid-rows-1 gap-10 md:grid-cols-2 md:grid-rows-2">
				<div className="flex flex-col items-center justify-center rounded-standard border-2 border-gray-300 px-2 py-4 text-center dark:border-white/[.13] md:px-20 md:py-10">
					<p className="text-xl md:text-2xl">🔎 Index Content Into Google</p>
					<p className="text-lg">
						Organically gain more users by ranking at the top of Google search
						results
					</p>
				</div>
				<div className="flex flex-col items-center justify-center rounded-standard border-2 border-gray-300 px-2 py-4 text-center dark:border-white/[.13] md:px-20 md:py-10">
					<p className="text-xl md:text-2xl">🤖 AI Question Answers</p>
					<p className="text-lg">
						<b>Automate answering repeat questions</b>, with AI answers sourced
						from your community content.
					</p>
				</div>
				<div className="flex flex-col items-center justify-center rounded-standard border-2 border-gray-300 px-2 py-4 text-center dark:border-white/[.13] md:px-20 md:py-10">
					<p className="text-xl md:text-2xl">📈 Community Insights</p>
					<p className="text-lg">
						Understand what your community is asking the most about and where to
						improve your documentation
					</p>
				</div>
				<div className="flex flex-col items-center justify-center rounded-standard border-2 border-gray-300 px-2 py-4 text-center dark:border-white/[.13] md:px-20 md:py-10">
					<p className="text-xl md:text-2xl">💻 Host On Your Own Domain</p>
					<p className="text-lg">
						Boost your website with organic content generated by your community
					</p>
				</div>
			</div>
		</div>
	);
};
