version: '3.8'

services:
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: "16"

    volumes:
      - ..:/workspace:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
    
  db-mysql:
    container_name: ao-db-sql    
    image: mysql:8.0.31-oracle
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    expose:
      - 3306
    ports:
      - 33306:3306
  
  db-elastic:
    container_name: ao-db-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    expose: 
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: ao-db-kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://ao-db-elastic:9200
    depends_on:
      - db-elastic
    expose:
      - 5601
    ports:
      - 5601:5601