version: '3.8'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "16"

    volumes:
      - ..:/AnswerOverflow:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
