import { ServerDashboard } from '@answeroverflow/api/src/router/dashboard';

export const demoServerData: ServerDashboard = {
	approximateMemberCount: 10000,
	bitfield: 0,
	customDomain: null,
	channels: [],
	description: null,
	flags: {
		anonymizeMessages: false,
		considerAllMessagesPublic: true,
		readTheRulesConsentEnabled: true,
	},
	icon: null,
	id: '1000',
	kickedTime: null,
	name: 'Demo Server',
	plan: 'FREE',
	stripeCustomerId: null,
	stripeSubscriptionId: null,
	vanityInviteCode: null,
	vanityUrl: null,
	dateCancelationTakesEffect: null,
	dateSubscriptionRenews: null,
	dateTrialEnds: null,
	enterprisePlanCheckoutUrl: null,
	hasSubscribedBefore: false,
	proPlanCheckoutUrl: null,
	status: 'inactive',
	stripeCheckoutUrl: undefined,
} as const;
